spring.application.name=DoencaChagas

# URL de conexão com o seu MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/aps_chagas_monitoramento
spring.datasource.username=root
spring.datasource.password=Fm020406@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 1. Desliga COMPLETAMENTE a criação de tabelas do Hibernate
spring.jpa.hibernate.ddl-auto=none
# Mostra o SQL gerado no console para te ajudar a debugar
spring.jpa.show-sql=true